### ISSUE TITLE
经常出现Invalid API key/secret.

### ISSUE THREAD

**Issue by ElfSundae** [ppyyf/notedup#1]
刚下载了notedup, 准备迁移到印象笔记. 感谢作者的工具. 
![qq20150129-1](https://cloud.githubusercontent.com/assets/526008/5948944/19ee889e-a784-11e4-8138-5163a5bbff4c.png)
发现个问题, 国际版授权经常出现这个错误, 关掉应用重试偶尔会正常. 貌似跟gfw有关系.. Mac版.

**Comment by ppyyf** [comment]
这种情况可能是网络问题导致的。可以试试VPN。目前notedup还不支持设置代理服务器。

**Comment by ElfSundae** [comment]
嗯,谢谢.
